// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PAGWv0Wfk1C62yl2S2tWMoIixknWCMI',
    appId: '1:140746465145:web:42efb6db8fb0293c0419a8',
    messagingSenderId: '140746465145',
    projectId: 'knue-moa',
    authDomain: 'knue-moa.firebaseapp.com',
    storageBucket: 'knue-moa.firebasestorage.app',
    measurementId: 'G-2LQZZ586FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnJgOEI1uC7E8QRvFhj01xJIIl6Z3-0M',
    appId: '1:140746465145:android:aec9054023db9c990419a8',
    messagingSenderId: '140746465145',
    projectId: 'knue-moa',
    storageBucket: 'knue-moa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7q7xXNhvUzWBnCE6vTQjUhU6SsBTTBM',
    appId: '1:140746465145:ios:fae8b158fc044e7b0419a8',
    messagingSenderId: '140746465145',
    projectId: 'knue-moa',
    storageBucket: 'knue-moa.firebasestorage.app',
    iosBundleId: 'com.knue.knuemoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7q7xXNhvUzWBnCE6vTQjUhU6SsBTTBM',
    appId: '1:140746465145:ios:fae8b158fc044e7b0419a8',
    messagingSenderId: '140746465145',
    projectId: 'knue-moa',
    storageBucket: 'knue-moa.firebasestorage.app',
    iosBundleId: 'com.knue.knuemoa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8PAGWv0Wfk1C62yl2S2tWMoIixknWCMI',
    appId: '1:140746465145:web:9f4bb7b02cc0f59f0419a8',
    messagingSenderId: '140746465145',
    projectId: 'knue-moa',
    authDomain: 'knue-moa.firebaseapp.com',
    storageBucket: 'knue-moa.firebasestorage.app',
    measurementId: 'G-GGBENFRN5N',
  );
}
